/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FontCheckRouteImport } from './routes/font-check'
import { Route as IndexRouteImport } from './routes/index'

const FontCheckRoute = FontCheckRouteImport.update({
  id: '/font-check',
  path: '/font-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/font-check': typeof FontCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/font-check': typeof FontCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/font-check': typeof FontCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/font-check'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/font-check'
  id: '__root__' | '/' | '/font-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontCheckRoute: typeof FontCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/font-check': {
      id: '/font-check'
      path: '/font-check'
      fullPath: '/font-check'
      preLoaderRoute: typeof FontCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontCheckRoute: FontCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
